Upgrade versions of requirements (#735)
* Upgrade versions of requirements

* Remove block that depended on a broken attribute jinja2.exceptions.UndefinedError: 'mkdocs.theme.Theme object' has no attribute 'feature'